"""
StreamContext Local Service v1.1
Upgraded with deep context carry — not just summaries
"""

import os
import json
import sqlite3
from datetime import datetime
from typing import List
from pathlib import Path

import anthropic
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()

app = FastAPI(title="StreamContext", version="1.1.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

DB_PATH = Path.home() / ".streamcontext" / "conversations.db"
DB_PATH.parent.mkdir(exist_ok=True)

def init_db():
    conn = sqlite3.connect(DB_PATH)
    conn.execute("CREATE TABLE IF NOT EXISTS conversations (id TEXT PRIMARY KEY, platform TEXT, url TEXT, title TEXT, created_at TEXT, updated_at TEXT, message_count INTEGER DEFAULT 0)")
    conn.execute("CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY AUTOINCREMENT, conversation_id TEXT, role TEXT, content TEXT, timestamp TEXT)")
    conn.execute("CREATE TABLE IF NOT EXISTS summaries (id INTEGER PRIMARY KEY AUTOINCREMENT, conversation_id TEXT, summary TEXT, created_at TEXT, message_count INTEGER)")
    conn.commit()
    conn.close()
init_db()

class Message(BaseModel):
    role: str
    content: str

class ConversationData(BaseModel):
    platform: str
    messages: List[Message]
    url: str
    title: str

class SummarizeRequest(BaseModel):
    messages: List[Message]
    platform: str

client = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

@app.get("/health")
def health():
    c = sqlite3.connect(DB_PATH)
    convs = c.execute("SELECT COUNT(*) FROM conversations").fetchone()[0]
    msgs = c.execute("SELECT COUNT(*) FROM messages").fetchone()[0]
    c.close()
    return {"status": "ok", "conversations": convs, "messages": msgs, "version": "1.1.0"}

@app.post("/conversations/{cid}/messages")
def save_messages(cid: str, data: ConversationData):
    c = sqlite3.connect(DB_PATH)
    now = datetime.now().isoformat()
    exists = c.execute("SELECT id FROM conversations WHERE id=?", (cid,)).fetchone()
    if exists:
        c.execute("UPDATE conversations SET updated_at=?, message_count=?, url=?, title=? WHERE id=?", (now, len(data.messages), data.url, data.title, cid))
    else:
        c.execute("INSERT INTO conversations VALUES (?,?,?,?,?,?,?)", (cid, data.platform, data.url, data.title, now, now, len(data.messages)))
    c.execute("DELETE FROM messages WHERE conversation_id=?", (cid,))
    for m in data.messages:
        c.execute("INSERT INTO messages (conversation_id,role,content,timestamp) VALUES (?,?,?,?)", (cid, m.role, m.content, now))
    c.commit(); c.close()
    return {"saved": len(data.messages)}

@app.post("/conversations/{cid}/summarize")
async def summarize(cid: str, data: SummarizeRequest):
    messages = data.messages
    if not messages:
        raise HTTPException(status_code=400, detail="No messages")

    total = len(messages)

    # Build FULL conversation text - use ALL messages, not just last 40
    # For very long convos, use smart chunking
    def build_conv_text(msgs, max_chars=80000):
        lines = []
        for m in msgs:
            role = "Human" if m.role == "user" else "Assistant"
            # Keep full content up to 3000 chars per message
            content = m.content[:3000]
            lines.append(f"{role}: {content}")
        full = "\n\n".join(lines)
        if len(full) <= max_chars:
            return full
        # If too long: keep first 20% (establishes context) + last 60% (recent work)
        first_cut = max_chars // 5
        last_cut = max_chars - first_cut - 200
        first_part = full[:first_cut]
        last_part = full[-last_cut:]
        middle_count = total - 20 - 20
        return f"{first_part}\n\n[... {middle_count} messages in the middle omitted for length ...]\n\n{last_part}"

    conv_text = build_conv_text(messages)

    # Upgraded deep context prompt
    deep_prompt = f"""You are helping continue an AI conversation in a fresh chat window. 
The user needs DEEP context — not a vague summary — so they can continue exactly where they left off.

This conversation had {total} messages total.

YOUR JOB: Create a "Context Transfer Document" that gives the new chat everything it needs.
Be SPECIFIC. Include actual values, file names, commands, code snippets, decisions.
Do NOT be vague. Do NOT generalize. Preserve specifics.

Structure your output EXACTLY like this:

# 🌊 StreamContext — Continuing Previous Conversation
*{total} messages transferred | Generated by StreamContext*

---

## 👤 Who I Am
[Key facts about the user: name, job, location, goals, setup]

## 🎯 What We Were Working On
[The specific task/project/goal at the moment of transfer]

## ✅ What Was Accomplished
[Bullet list of everything completed — be specific with file names, commands, outputs]

## 🔧 Current State
[Exact state of things right now — what's running, what's configured, what's broken]

## 💾 Key Details & Specifics
[All the important specifics: API keys mentioned, file paths, config values, URLs, credentials discussed, commands that worked/failed]

## 🐛 Issues & Solutions Found
[Problems encountered and how they were solved — or if still unsolved]

## 💡 Decisions Made
[Key decisions and the reasoning behind them]

## 📋 Exact Next Steps
[What we were about to do next, in order]

## 🗣️ Last Exchange
[The last 3-5 exchanges verbatim so the new chat has immediate context]

---
*Please read all of the above carefully and continue exactly where we left off. You know everything about this conversation now.*

CONVERSATION TO ANALYZE:
{conv_text}

Generate the Context Transfer Document now:"""

    try:
        # Use Sonnet for better quality on deep context
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=4000,
            messages=[{"role": "user", "content": deep_prompt}]
        )
        summary = response.content[0].text

        c = sqlite3.connect(DB_PATH)
        c.execute("INSERT INTO summaries (conversation_id,summary,created_at,message_count) VALUES (?,?,?,?)", (cid, summary, datetime.now().isoformat(), total))
        c.commit(); c.close()

        return {"summary": summary, "message_count": total, "model": "claude-sonnet-4-6"}

    except Exception as e:
        # Fallback: include raw recent messages if AI fails
        recent = messages[-15:]
        fallback = f"# Continuing Previous Conversation\n\n*{total} total messages. Last {len(recent)} shown:*\n\n"
        for m in recent:
            role = "You" if m.role == "user" else "AI"
            fallback += f"**{role}:** {m.content[:800]}\n\n---\n\n"
        fallback += "\nPlease continue from where we left off."
        return {"summary": fallback, "message_count": total, "fallback": True, "error": str(e)}

@app.get("/conversations")
def list_conversations():
    c = sqlite3.connect(DB_PATH)
    rows = c.execute("SELECT id,platform,title,message_count,created_at,updated_at FROM conversations ORDER BY updated_at DESC LIMIT 50").fetchall()
    c.close()
    return [{"id":r[0],"platform":r[1],"title":r[2],"message_count":r[3],"created_at":r[4],"updated_at":r[5]} for r in rows]

@app.get("/conversations/{cid}")
def get_conversation(cid: str):
    c = sqlite3.connect(DB_PATH)
    conv = c.execute("SELECT * FROM conversations WHERE id=?", (cid,)).fetchone()
    if not conv: raise HTTPException(status_code=404, detail="Not found")
    msgs = c.execute("SELECT role,content FROM messages WHERE conversation_id=? ORDER BY id", (cid,)).fetchall()
    c.close()
    return {"id":conv[0],"platform":conv[1],"url":conv[2],"title":conv[3],"messages":[{"role":m[0],"content":m[1]} for m in msgs]}

@app.get("/", response_class=HTMLResponse)
def archive_ui():
    return """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>StreamContext Archive</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'JetBrains Mono', monospace; background: #0a0a1a; color: #e8e8f0; min-height: 100vh; }
.header { padding: 24px 32px; background: #111128; border-bottom: 1px solid rgba(0,200,255,0.15); display: flex; align-items: center; gap: 12px; }
.logo { font-size: 28px; } .title { font-size: 20px; font-weight: 700; color: #00c8ff; } .subtitle { font-size: 11px; color: #555; margin-top: 2px; }
.content { max-width: 900px; margin: 32px auto; padding: 0 32px; }
.section-label { font-size: 10px; letter-spacing: 2px; color: #555; text-transform: uppercase; margin-bottom: 12px; }
.conv-list { display: flex; flex-direction: column; gap: 8px; }
.conv-card { background: #111128; border: 1px solid rgba(255,255,255,0.06); border-radius: 10px; padding: 16px; cursor: pointer; transition: all 0.2s; }
.conv-card:hover { border-color: rgba(0,200,255,0.2); }
.conv-title { font-size: 13px; font-weight: 600; margin-bottom: 4px; }
.conv-meta { font-size: 10px; color: #555; display: flex; gap: 12px; }
.platform-badge { padding: 2px 8px; border-radius: 8px; font-size: 9px; font-weight: 600; text-transform: uppercase; }
.platform-claude { background: rgba(255,100,50,0.15); color: #ff6432; }
.platform-chatgpt { background: rgba(16,163,127,0.15); color: #10a37f; }
.msg-count { background: rgba(0,200,255,0.1); color: #00c8ff; padding: 2px 6px; border-radius: 6px; font-size: 9px; }
.stats-row { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 24px; }
.stat-box { background: #111128; border: 1px solid rgba(255,255,255,0.06); border-radius: 10px; padding: 16px; text-align: center; }
.stat-num { font-size: 24px; font-weight: 700; color: #00c8ff; } .stat-label { font-size: 10px; color: #555; margin-top: 4px; }
.empty { text-align: center; padding: 60px; color: #555; }
.version { font-size: 9px; color: #333; text-align: right; padding: 8px 32px; }
</style>
</head>
<body>
<div class="header"><span class="logo">🌊</span><div><div class="title">StreamContext Archive v1.1</div><div class="subtitle">Deep context transfer — never lose a conversation</div></div></div>
<div class="content">
  <div class="stats-row" id="stats"></div>
  <div class="section-label">Recent Conversations</div>
  <div class="conv-list" id="conv-list"><div class="empty">No conversations yet. Start chatting on Claude.ai or ChatGPT!</div></div>
</div>
<div class="version">StreamContext v1.1 — Deep Context Transfer</div>
<script>
async function load() {
  try {
    const h = await fetch('/health').then(r=>r.json());
    document.getElementById('stats').innerHTML = `<div class="stat-box"><div class="stat-num">${h.conversations}</div><div class="stat-label">Conversations</div></div><div class="stat-box"><div class="stat-num">${h.messages}</div><div class="stat-label">Messages</div></div><div class="stat-box"><div class="stat-num">100%</div><div class="stat-label">Local & Private</div></div>`;
    const c = await fetch('/conversations').then(r=>r.json());
    if(c.length>0) document.getElementById('conv-list').innerHTML = c.map(x=>`<div class="conv-card" onclick="window.open('/conversations/${x.id}','_blank')"><div class="conv-title">${x.title||'Untitled'}</div><div class="conv-meta"><span class="platform-badge platform-${x.platform}">${x.platform}</span><span class="msg-count">${x.message_count} messages</span><span>${new Date(x.updated_at).toLocaleDateString()}</span></div></div>`).join('');
  } catch(e) { console.error(e); }
}
load();
</script>
</body>
</html>"""

if __name__ == "__main__":
    import uvicorn
    print("🌊 StreamContext v1.1 — Deep Context Transfer")
    print("📍 Running at: http://localhost:7892")
    print("🔑 API Key:", "✓ Set" if os.getenv("ANTHROPIC_API_KEY") else "✗ Missing")
    uvicorn.run(app, host="127.0.0.1", port=7892, log_level="warning")
